ExamenMVC/ExamenMVC.Web/Controllers/FacturaController.cs
using ExamenMVC.Repositorio.Comun;
using ExamenMVC.Web.Funcionalidades.Handlers.Facturas;
using ExamenMVC.Web.Funcionalidades.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenMVC.Web.Controllers
{
    public class FacturaController : Controller
    {
        // GET: Factura
        public ActionResult Ver(int id)
        {
            using (var list = new VerFacturaHandler())
            {
                return View(list.Execute(id));
            }
        }
        
        [HttpGet]
        public ActionResult Registrar(int id)
        {
            ViewBag.Id = id;
            return View(new RegistrarFacturaViewModel());
        }

        [HttpPost]
        public ActionResult Registrar(RegistrarFacturaViewModel modelo, int id, HttpPostedFileBase image)
        {
            string ruta = Server.MapPath("~/imagenes/Facturas");
            ViewBag.Id = id;
            modelo.EmpresaId = ViewBag.Id;            
            if (!ModelState.IsValid) return View(modelo);
            using (var registra = new RegistrarFacturaHandler())
            {
                try
                {
                    Imagen imagen = ObtenerImagen(image, ruta);
                    registra.GrabarImgFactura(modelo, imagen);
                    return RedirectToAction("Ver", "Factura", new { id = ViewBag.Id });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }

        private Imagen ObtenerImagen(HttpPostedFileBase image, string ruta)
        {
            if (image == null) return null;
            var stream = new MemoryStream();

            image.InputStream.CopyTo(stream);
            return new Imagen(stream, image.FileName, image.ContentType, ruta);
        }

        [HttpGet]
        public PartialViewResult Editar(int id)
        {
            using (var buscar = new EditarFacturaHandler())
            {
                TempData["empid"] = buscar.Execute(id).EmpresaId;
                return PartialView("Editar", buscar.Execute(id));
            }
        }

        [HttpPost]
        public ActionResult Editar(EditarFacturaViewModel modelo, HttpPostedFileBase image)
        {
            string ruta = Server.MapPath("~/imagenes/Facturas");
            modelo.EmpresaId = Convert.ToInt32(TempData["empid"]);
            if (!ModelState.IsValid) return View(modelo);
            using (var edita = new EditarFacturaHandler())
            {
                try
                {
                    Imagen imagen = ObtenerImagen(image, ruta);
                    edita.GrabarImgFactura(modelo, imagen);
                    return RedirectToAction("Lista", "Empresa");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }

        [HttpGet]
        public PartialViewResult Eliminar(int id)
        {
            using (var ver = new EliminarFacturaHandler())
            {
                return PartialView("Eliminar", ver.Execute(id));
            }
        }

        [HttpPost]
        public ActionResult Eliminar(VerFacturaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);
            using (var elimina = new EliminarFacturaHandler())
            {
                try
                {
                    elimina.EliminarFactura(modelo);
                    return RedirectToAction("Lista", "Empresa");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }
            }
        }
    }
}

ExamenMVC/ExamenMVC.Web/Controllers/ImagenesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenMVC.Web.Controllers
{
    public class ImagenesController : Controller
    {
        // GET: Imagenes
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(CacheProfile = "FacturaImages")]
        public FileResult Show(string id, string ext)
        {
            var path = Path
                .Combine(Server.MapPath("~/Imagenes/Facturas"), id + $".{ext}");
            return new FileStreamResult(
                    new FileStream(path, FileMode.Open),
                    MimeMapping.GetMimeMapping($"{id}.{ext}"));
        }
    }
}

ExamenMVC/ExamenMVC.Web/Views/Factura/Editar.cshtml
@model ExamenMVC.Web.Funcionalidades.ViewModels.EditarFacturaViewModel

<div id="EditFactura">
@using (Html.BeginForm("Editar","Factura", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-hidden="true">
                    &times;
                </button>
                <h4>Editando Factura: @Model.RazonSocialCliente</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.Numero)
                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaEmision, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaEmision, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FechaEmision, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaVencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaVencimiento, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FechaVencimiento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaCobro, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaCobro, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FechaCobro, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RucCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RucCliente, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RucCliente, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.RazonSocialCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RazonSocialCliente, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RazonSocialCliente, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TotalFactura, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TotalFactura, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TotalFactura, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TotalImpuesto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TotalImpuesto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TotalImpuesto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.HiddenFor(model => model.ImagenMini)
                    <div class="form-group">
                        <div class="row">
                            @Html.LabelFor(model => model.ImagenMini, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                <input type="file" name="image" class="form-control" />
                                @Html.ValidationMessageFor(model => model.ImagenMini, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-4">
                                <img src="@Url.Action("Show","Imagenes", new { id = Model.ImagenMini, ext=Model.ImagenMiniExtension})" />
                            </div>
                        </div>
                    </div>
                    <div>
                        @Html.HiddenFor(model => model.EmpresaId)
                    </div>                    
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                        </div>
                    </div>
                </div>                    
                </div>
            </div>
        </div>
}
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusiveajax")
}

ExamenMVC/ExamenMVC.Web/Views/Factura/Eliminar.cshtml
@model ExamenMVC.Web.Funcionalidades.ViewModels.VerFacturaViewModel

<div id="DeleteFactura">
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <h3>¿Está seguro de eliminar este registro?</h3>
                </div>
                <div class="modal-body">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.FechaEmision)
                        </dt>

                        <dd>
                            @Html.HiddenFor(model => model.Numero)
                            @Html.DisplayFor(model => model.FechaEmision)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.RucCliente)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.RucCliente)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.RazonSocialCliente)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.RazonSocialCliente)
                        </dd>
                    </dl>

                </div>
                <div class="modal-footer">
                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                    </div>
                </div>                    
            </div>
        </div>
    }
</div>

ExamenMVC/ExamenMVC.Web/Views/Factura/Registrar.cshtml
@model ExamenMVC.Web.Funcionalidades.ViewModels.RegistrarFacturaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar Factura</h2>


@using (Html.BeginForm("Registrar", "Factura", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @Html.HiddenFor(model => model.Numero)

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEmision, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 190px;">
                @Html.EditorFor(model => model.FechaEmision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEmision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaVencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 190px;">
                @Html.EditorFor(model => model.FechaVencimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaVencimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCobro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 190px;">
                @Html.EditorFor(model => model.FechaCobro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCobro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RucCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 170px;">
                @Html.EditorFor(model => model.RucCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RucCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocialCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocialCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocialCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalFactura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 120px;">
                @Html.EditorFor(model => model.TotalFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalFactura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalImpuesto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="width: 120px;">
                @Html.EditorFor(model => model.TotalImpuesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalImpuesto, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ImagenMini)
        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.ImagenMini, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <input type="file" name="image" class="form-control" />
                    @Html.ValidationMessageFor(model => model.ImagenMini, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    <img src="@Url.Action("Show","Imagenes", new { id = Model.ImagenMini, ext=Model.ImagenMiniExtension})" />
                </div>
            </div>
        </div>

        <div class="form-group">            
            <div class="col-md-10">
                @*@Html.HiddenFor(model => model.EmpresaId)
                @Html.ValueFor(model => model.EmpresaId)*@
                @ViewBag.Id
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Lista", "Empresa")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExamenMVC/ExamenMVC.Web/Views/Factura/Ver.cshtml
@model IEnumerable<ExamenMVC.Web.Funcionalidades.ViewModels.VerFacturaViewModel>

@{
    ViewBag.Title = "Ver";
}

<h2>Ver Factura</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaEmision)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RucCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazonSocialCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalFactura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalImpuesto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>        
        <td>
            @Html.HiddenFor(modelItem => item.EmpresaId)            
            @Html.DisplayFor(modelItem => item.Numero)
        </td>
        <td>            
            @Html.DisplayFor(modelItem => item.FechaEmision)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RucCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RazonSocialCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalFactura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalImpuesto)
        </td>        
        <td>
            <div class="btn-group">
                <button class="btn dropdown-toggle btn-xs"
                        data-toggle="dropdown">
                    <span>
                        <i class="glyphicon glyphicon-cog"></i>
                        <span class="caret"></span>
                    </span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        @Ajax.ActionLink(" Editar", "Editar", "Factura"
                                , new { id = item.Numero }
                                , new AjaxOptions
                                {
                                    HttpMethod = "Get",
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "EditarFacturaForm"
                                }
                                ,
                                new
                                {
                                    @class = "glyphicon glyphicon-edit",
                                    data_toggle = "modal",
                                    data_target = "#EditarFacturaForm"
                                }
                            )
                    </li>
                    <li>

                        @Ajax.ActionLink(" Eliminar", "Eliminar", "Factura"
                                    , new { id = item.Numero }
                                    , new AjaxOptions
                                    {
                                        HttpMethod = "Get",
                                        InsertionMode = InsertionMode.Replace,
                                        UpdateTargetId = "EliminarFacturaForm"
                                    }
                                    ,
                                    new
                                    {
                                        @class = "glyphicon glyphicon-trash",
                                        data_toggle = "modal",
                                        data_target = "#EliminarFacturaForm"
                                    })
                    </li>
                </ul>
            </div>
        </td>
    </tr>
}               

</table>

<div>
    @Html.ActionLink("Regresar a Empresas", "Lista", "Empresa")
</div>

<div id="EditarFacturaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EditarFacturaFormlabel"
     aria-hidden="true">
</div>

<div id="EliminarFacturaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EliminarFacturalabel"
     aria-hidden="true">
</div>